In [1]:
import matplotlib.pyplot as pt
import pandas as pd


data = pd.read_csv('energydata_trainning.csv')
temp_humidity = data[['T1','RH_1','Day_of_week']]
temp_humidity

              T1       RH_1 Day_of_week
0      19.890000  47.596667      Monday
1      19.890000  46.693333      Monday
2      19.890000  46.300000      Monday
3      19.890000  46.333333      Monday
4      19.890000  46.026667      Monday
5      19.856667  45.560000      Monday
6      19.790000  45.597500      Monday
7      19.856667  46.090000      Monday
8      20.133333  48.000000      Monday
9      20.260000  52.726667      Monday
10     20.426667  55.893333      Monday
11     20.730000  52.660000      Monday
12     20.890000  51.193333      Monday
13     20.890000  49.800000      Monday
14     20.890000  48.433333      Monday
15     21.100000  46.596667      Monday
16     21.133333  46.060000      Monday
17     21.200000  45.800000      Monday
18     21.290000  45.900000      Monday
19     21.390000  45.690000      Monday
20     21.500000  45.333333      Monday
21     21.500000  45.126667      Monday
22     21.533333  44.966667      Monday
23     21.600000  44.766667      Monday
24     21.600000  44.560000      Monday
25     21.600000  44.360000      Monday
26     21.600000  44.200000      Monday
27     21.600000  44.200000      Monday
28     21.600000  44.200000      Monday
29     21.500000  44.230000      Monday
...          ...        ...         ...
14773  24.760000  47.926667      Friday
14774  24.823333  47.790000      Friday
14775  24.890000  47.790000      Friday
14776  24.890000  47.790000      Friday
14777  24.890000  47.730000      Friday
14778  25.033333  48.363333      Friday
14779  25.166667  48.156667      Friday
14780  25.323333  47.930000      Friday
14781  25.390000  47.656667      Friday
14782  25.500000  47.060000      Friday
14783  25.600000  46.990000      Friday
14784  25.600000  46.730000      Friday
14785  25.500000  46.360000      Friday
14786  25.500000  46.060000      Friday
14787  25.500000  45.933333      Friday
14788  25.500000  45.760000      Friday
14789  25.500000  45.626667      Friday
14790  25.500000  45.590000      Friday
14791  25.500000  45.522500      Friday
14792  25.500000  45.730000      Friday
14793  25.500000  45.790000      Friday
14794  25.500000  45.933333      Friday
14795  25.426667  46.060000      Friday
14796  25.500000  46.530000      Friday
14797  25.500000  47.456667      Friday
14798  25.600000  47.193333      Friday
14799  25.533333  46.860000      Friday
14800  25.500000  46.500000      Friday
14801  25.500000  46.990000      Friday
14802  25.500000  46.600000      Friday

[14803 rows x 3 columns]

In [2]:
temp_humidity_saturday = temp_humidity[data.Day_of_week == 'Saturday']
temp_humidity_saturday

              T1       RH_1 Day_of_week
471    23.000000  40.000000    Saturday
472    22.890000  40.126667    Saturday
473    22.890000  40.200000    Saturday
474    22.790000  40.090000    Saturday
475    22.790000  40.163333    Saturday
476    22.760000  40.230000    Saturday
477    22.700000  40.290000    Saturday
478    22.666667  40.290000    Saturday
479    22.600000  40.290000    Saturday
480    22.500000  40.290000    Saturday
481    22.390000  40.200000    Saturday
482    22.356667  40.200000    Saturday
483    22.290000  40.200000    Saturday
484    22.200000  40.090000    Saturday
485    22.200000  40.090000    Saturday
486    22.166667  40.090000    Saturday
487    22.100000  40.090000    Saturday
488    22.066667  40.060000    Saturday
489    21.963333  40.000000    Saturday
490    21.890000  40.000000    Saturday
491    21.890000  40.000000    Saturday
492    21.890000  40.000000    Saturday
493    21.700000  39.900000    Saturday
494    21.500000  39.900000    Saturday
495    21.426667  39.933333    Saturday
496    21.390000  39.900000    Saturday
497    21.390000  39.900000    Saturday
498    21.356667  39.933333    Saturday
499    21.230000  40.030000    Saturday
500    21.200000  39.863333    Saturday
...          ...        ...         ...
14150  24.892286  46.409143    Saturday
14151  24.945000  46.245000    Saturday
14152  24.890000  46.400000    Saturday
14153  24.862727  46.819455    Saturday
14154  24.858182  46.889364    Saturday
14155  24.853636  46.959273    Saturday
14156  24.849091  47.029182    Saturday
14157  24.840000  47.169000    Saturday
14158  24.835455  47.238909    Saturday
14159  24.826364  47.378727    Saturday
14160  24.821818  47.448636    Saturday
14161  24.817273  47.518545    Saturday
14162  24.812727  47.588455    Saturday
14163  24.803636  47.728273    Saturday
14164  24.794545  47.868091    Saturday
14165  24.790000  47.938000    Saturday
14166  24.785455  48.007909    Saturday
14167  24.776364  48.147727    Saturday
14168  24.771818  48.217636    Saturday
14169  24.767273  48.287545    Saturday
14170  24.762727  48.357455    Saturday
14171  24.758182  48.427364    Saturday
14172  24.753636  48.497273    Saturday
14173  24.749091  48.567182    Saturday
14174  24.744545  48.637091    Saturday
14175  24.740000  48.707000    Saturday
14176  24.726364  48.916727    Saturday
14177  24.721818  48.986636    Saturday
14178  24.717273  49.056545    Saturday
14179  24.712727  49.126455    Saturday

[2022 rows x 3 columns]

In [4]:
avg_temp_saturday = temp_humidity_saturday['T1'].mean()
avg_temp_saturday

21.59019933758942

In [5]:
temp_humidity_sunday = temp_humidity[data.Day_of_week == 'Sunday']
temp_humidity_sunday

              T1       RH_1 Day_of_week
571    22.500000  39.363333      Sunday
572    22.426667  39.290000      Sunday
573    22.323333  39.363333      Sunday
574    22.230000  39.500000      Sunday
575    22.200000  39.500000      Sunday
576    22.133333  39.560000      Sunday
577    22.066667  39.663333      Sunday
578    22.000000  39.663333      Sunday
579    22.000000  39.700000      Sunday
580    21.790000  39.700000      Sunday
581    21.760000  39.790000      Sunday
582    21.700000  39.790000      Sunday
583    21.500000  40.000000      Sunday
584    21.426667  40.030000      Sunday
585    21.390000  40.000000      Sunday
586    21.390000  40.060000      Sunday
587    21.290000  40.090000      Sunday
588    21.290000  40.090000      Sunday
589    21.290000  40.200000      Sunday
590    21.230000  40.200000      Sunday
591    21.200000  40.200000      Sunday
592    21.100000  40.290000      Sunday
593    21.100000  40.290000      Sunday
594    21.100000  40.290000      Sunday
595    21.000000  40.290000      Sunday
596    21.000000  40.363333      Sunday
597    21.000000  40.400000      Sunday
598    21.000000  40.400000      Sunday
599    20.963333  40.433333      Sunday
600    20.890000  40.500000      Sunday
...          ...        ...         ...
14258  24.890000  53.156667      Sunday
14259  24.890000  53.363333      Sunday
14260  24.890000  53.163333      Sunday
14261  24.890000  53.030000      Sunday
14262  24.890000  52.633333      Sunday
14263  24.890000  52.433333      Sunday
14264  24.890000  52.290000      Sunday
14265  24.890000  51.900000      Sunday
14266  24.890000  51.566667      Sunday
14267  24.963333  51.363333      Sunday
14268  24.890000  51.230000      Sunday
14269  24.890000  50.966667      Sunday
14270  24.890000  50.826667      Sunday
14271  24.890000  50.590000      Sunday
14272  24.963333  50.390000      Sunday
14273  24.945000  50.090000      Sunday
14274  24.890000  50.126667      Sunday
14275  24.890000  50.200000      Sunday
14276  24.890000  50.060000      Sunday
14277  24.890000  49.933333      Sunday
14278  24.890000  49.863333      Sunday
14279  24.856667  49.663333      Sunday
14280  24.790000  49.530000      Sunday
14281  24.700000  49.126667      Sunday
14282  24.700000  49.000000      Sunday
14283  24.700000  48.933333      Sunday
14284  24.666667  48.833333      Sunday
14285  24.600000  48.700000      Sunday
14286  24.600000  48.590000      Sunday
14287  24.600000  48.590000      Sunday

[2061 rows x 3 columns]

In [6]:
avg_temp_sunday = temp_humidity_sunday['T1'].mean()
avg_temp_sunday

21.811175584079333

In [7]:
avg_humidity_saturday = temp_humidity_saturday['RH_1'].mean()
avg_humidity_saturday

40.027873782333224