In [24]:
import matplotlib.pyplot as pt
import pandas as pd


data = pd.read_csv('energydata_trainning.csv')
data[['T1','RH_1','Day_of_week']]

              T1       RH_1 Day_of_week
0      19.890000  47.596667      Monday
1      19.890000  46.693333      Monday
2      19.890000  46.300000      Monday
3      19.890000  46.333333      Monday
4      19.890000  46.026667      Monday
5      19.856667  45.560000      Monday
6      19.790000  45.597500      Monday
7      19.856667  46.090000      Monday
8      20.133333  48.000000      Monday
9      20.260000  52.726667      Monday
10     20.426667  55.893333      Monday
11     20.730000  52.660000      Monday
12     20.890000  51.193333      Monday
13     20.890000  49.800000      Monday
14     20.890000  48.433333      Monday
15     21.100000  46.596667      Monday
16     21.133333  46.060000      Monday
17     21.200000  45.800000      Monday
18     21.290000  45.900000      Monday
19     21.390000  45.690000      Monday
20     21.500000  45.333333      Monday
21     21.500000  45.126667      Monday
22     21.533333  44.966667      Monday
23     21.600000  44.766667      Monday
24     21.600000  44.560000      Monday
25     21.600000  44.360000      Monday
26     21.600000  44.200000      Monday
27     21.600000  44.200000      Monday
28     21.600000  44.200000      Monday
29     21.500000  44.230000      Monday
...          ...        ...         ...
14773  24.760000  47.926667      Friday
14774  24.823333  47.790000      Friday
14775  24.890000  47.790000      Friday
14776  24.890000  47.790000      Friday
14777  24.890000  47.730000      Friday
14778  25.033333  48.363333      Friday
14779  25.166667  48.156667      Friday
14780  25.323333  47.930000      Friday
14781  25.390000  47.656667      Friday
14782  25.500000  47.060000      Friday
14783  25.600000  46.990000      Friday
14784  25.600000  46.730000      Friday
14785  25.500000  46.360000      Friday
14786  25.500000  46.060000      Friday
14787  25.500000  45.933333      Friday
14788  25.500000  45.760000      Friday
14789  25.500000  45.626667      Friday
14790  25.500000  45.590000      Friday
14791  25.500000  45.522500      Friday
14792  25.500000  45.730000      Friday
14793  25.500000  45.790000      Friday
14794  25.500000  45.933333      Friday
14795  25.426667  46.060000      Friday
14796  25.500000  46.530000      Friday
14797  25.500000  47.456667      Friday
14798  25.600000  47.193333      Friday
14799  25.533333  46.860000      Friday
14800  25.500000  46.500000      Friday
14801  25.500000  46.990000      Friday
14802  25.500000  46.600000      Friday

[14803 rows x 3 columns]

In [26]:
data['Day_of_week'] = 'Monday'